development:
    vkontakte:
        app_id: 3952126
        app_secret: 4m0TyOhp0Ohm5X94WIKa
    
    facebook:
        app_id: 509688585768674
        app_secret: 29c826d573c1b4fee9035c5a32c88b19
  
test:
    vkontakte:
        app_id: 3952126
        app_secret: 4m0TyOhp0Ohm5X94WIKa
    
    facebook:
        app_id: 509688585768674
        app_secret: 29c826d573c1b4fee9035c5a32c88b19
staging:
    vkontakte:
        app_id: 3952126
        app_secret: 4m0TyOhp0Ohm5X94WIKa
    
    facebook:
        app_id: 509688585768674
        app_secret: 29c826d573c1b4fee9035c5a32c88b19
   
production:
    vkontakte:
        app_id: 3952126
        app_secret: 4m0TyOhp0Ohm5X94WIKa
    
    facebook:
        app_id: 509688585768674
        app_secret: 29c826d573c1b4fee9035c5a32c88b19
 
